services:
  postgres-api:
    image: postgres:14.3
    container_name: tweet-database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'tweet_development'
      POSTGRES_USER: 'tweet'
      POSTGRES_PASSWORD: 'tweet'
      ADDITIONAL_POSTGRES_DB: 'tweet_test'
    volumes:
      - ./databases/init-scripts:/docker-entrypoint-initdb.d
  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: tweet-rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
